### ISSUE TITLE
Spacing is off on workshop leaders heading

### ISSUE THREAD

**Issue by alexclarkofficial** [LibertyJS/libertyjs2017#54]

**Comment by belcherj** [comment]
I am not seeing this issue, can we close?  If not please add ascreengrab.

**Comment by alexclarkofficial** [comment]
<img width="1440" alt="screen shot 2017-11-12 at 5 16 48 pm" src="https://user-images.githubusercontent.com/4665704/32704055-554c3a96-c7cd-11e7-80c8-5e9fdaf8b22e.png">

**Comment by belcherj** [comment]
fixed
